"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --------------------------------------------------------------------------
# Security
# --------------------------------------------------------------------------

SECRET_KEY = config('SECRET_KEY', default='django-insecure-dev-key')
DEBUG = config('DEBUG', default=True, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*').split(',')


# --------------------------------------------------------------------------
# Applications
# --------------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'drf_spectacular',
    # Local
    'core',
    'shortener',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# --------------------------------------------------------------------------
# Databases
# --------------------------------------------------------------------------
# Primary (read-write) database.
# Set DATABASE_URL in .env to use PostgreSQL in production.
# --------------------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

_db_url = config('DATABASE_URL', default='')
if _db_url:
    from urllib.parse import urlparse as _urlparse
    _u = _urlparse(_db_url)
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _u.path[1:],
        'USER': _u.username,
        'PASSWORD': _u.password,
        'HOST': _u.hostname,
        'PORT': _u.port,
    }

# --------------------------------------------------------------------------
# Analytics read replica (optional)
# --------------------------------------------------------------------------
# Set ANALYTICS_REPLICA_URL in .env to route Click reads to a separate DB.
# If not set, falls back to 'default' transparently.
# --------------------------------------------------------------------------

_replica_url = config('ANALYTICS_REPLICA_URL', default='')
if _replica_url:
    from urllib.parse import urlparse as _urlparse
    _r = _urlparse(_replica_url)
    DATABASES['analytics_replica'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _r.path[1:],
        'USER': _r.username,
        'PASSWORD': _r.password,
        'HOST': _r.hostname,
        'PORT': _r.port,
        'TEST': {'MIRROR': 'default'},  # mirrors default in tests
    }
else:
    # Mirror default so the router still works without a real replica
    DATABASES['analytics_replica'] = DATABASES['default'].copy()
    DATABASES['analytics_replica']['TEST'] = {'MIRROR': 'default'}

# Register the router
DATABASE_ROUTERS = ['config.routers.AnalyticsReplicaRouter']


# --------------------------------------------------------------------------
# Caching
# --------------------------------------------------------------------------
# Use Redis in production (set REDIS_URL in .env).
# Falls back to LocMemCache in development so no external dependency needed.
# --------------------------------------------------------------------------

_redis_url = config('REDIS_URL', default='')

if _redis_url:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _redis_url,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'urlshortener',
            'TIMEOUT': 60 * 15,  # 15 minutes default TTL
        }
    }
else:
    # Development fallback — no Redis required
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'urlshortener-dev',
        }
    }


# --------------------------------------------------------------------------
# Authentication
# --------------------------------------------------------------------------

AUTH_USER_MODEL = 'core.User'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --------------------------------------------------------------------------
# Internationalisation
# --------------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --------------------------------------------------------------------------
# Django REST Framework & Spectacular
# --------------------------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'URL Shortener API',
    'DESCRIPTION': 'Enterprise-Grade URL Shortener Microservice',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
