# Generated by Django 5.0.14 on 2026-04-28 20:24

from django.db import migrations

def create_default_tags(apps, schema_editor):
    Tag = apps.get_model('shortener', 'Tag')
    default_tags = ['Marketing', 'Social', 'Personal', 'Business', 'Event']
    for tag in default_tags:
        Tag.objects.get_or_create(name=tag)

def remove_default_tags(apps, schema_editor):
    Tag = apps.get_model('shortener', 'Tag')
    default_tags = ['Marketing', 'Social', 'Personal', 'Business', 'Event']
    Tag.objects.filter(name__in=default_tags).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_tag_url_click_count_url_created_at_url_custom_alias_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_tags, remove_default_tags),
    ]
