# Generated by Django 5.0.14 on 2026-04-29 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_seed_default_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='click',
            options={'ordering': ['-clicked_at'], 'verbose_name': 'Click Analytics', 'verbose_name_plural': 'Click Analytics'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['-created_at'], 'verbose_name': 'URL', 'verbose_name_plural': 'URLs'},
        ),
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['short_code'], name='shortener_u_short_c_50dfff_idx'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['created_at'], name='shortener_u_created_364eca_idx'),
        ),
    ]
